### PR TITLE
Update: NarNode: Allow Shell.

### PR DESCRIPTION
**Pull request by patham9**

### CODE REVIEW

**Comment by PtrMan** [comment]
It's called a Nar but isn't a Nar :)

**Comment by patham9** [comment]
I noticed that Inheritance has some issues compared to Composition.
One that came into my way: Imagine there are multiple wrappers that add functionality to a Nar, NarNode being the one that adds network communication ability, NARSwing the one that add a GUI interface, Shell the one that adds console I/O. Multiple inheritance wouldn't be allowed and couldn't capture it, but composition allows us to attach the GUI and the network functionality to the very same Nar instance.

**Comment by PtrMan** [comment]
Ah your right and I were right - good

**Comment by PtrMan** [comment]
Tony is right, too - composition is the way to go most of the time. Except where the Liskov substitution principle applies :)

**Pull request merged**
